spring:
  application:
    name: stocktracker
  data:
    mongodb:
      host: localhost
      port: 27017
      database: stocktracker

stock:
  client:
    brapi:
      url: https://brapi.dev/api/quote
      token: ${BRAPI_API_TOKEN}
